repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
      - id: format
        name: code-formatter
        entry: make format
        language: system
      - id: pytest
        name: test-check
        entry: make test
        language: system
